---

- hosts: all
  become: true
  tasks:

  - name: install apache and php package
    package:
      name: 
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
      state: latest
      update_cache: yes
