---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian)
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install updates (Pop!_OS)
    tags: always
# Could be a dnf-based distro theoretically,
# so the commands would be different
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Pop!_OS"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Debianserver
    tags: apache,apache2,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: install apache and php for LenovoTPT530
    tags: apache,apache2,popos
# Could be a dnf-based distro theoretically,
# so the package name would be different
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Pop!_OS"


- hosts: db_servers
  become: true
  tasks:

  - name: install MariaDB for Debianserver
    tags: db,mariadb,debian
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

  - name: install MariaDB for LenovoTPT530
    tags: db,mariadb,popos
# Could be a dnf-based distro theoretically,
# so the package name would be different
    apt:
      name:
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Pop!_OS"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    tags: samba
# Package name is identically for both apt and dnf
    package:
      name:
        - samba
      state: latest
