---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache for Debianserver-VM and LenovoTPT530
    tags: always
    apt: 
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian","Pop!_OS"]

  - name: update repo cache for FedoraWS-VM
    tags: always
    dnf: 
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Fedora"


- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
